- name: Set Password Never Expires for system users
  win_shell: |
    Import-Module ActiveDirectory

    $user = Get-ADUser -Server {{ domain }} -Identity {{ item }}              \
      -Properties PasswordNeverExpires
    if ($user.PasswordNeverExpires -eq $true) {
      exit 255
    }

    Set-ADUser -Server {{ domain }} -Identity {{ item }}                      \
      -PasswordNeverExpires $true
  register: result
  failed_when: "result.rc != 255 and result.rc != 0"
  changed_when: "result.rc == 0"
  with_items:
  - Administrator
  - vagrant
